# Generated by Django 4.2.28 on 2026-02-13 09:57

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("employee", "Çalışan"),
                            ("manager", "Ekip Yöneticisi"),
                        ],
                        default="employee",
                        max_length=20,
                        verbose_name="Rolü",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Unvan / Sicil Bilgisi"
                    ),
                ),
                (
                    "team",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("team1", "Yazılım Geliştirme Ekibi"),
                            ("team2", "Test ve Kalite Ekibi"),
                            ("team3", "DevOps Ekibi"),
                        ],
                        max_length=50,
                        null=True,
                        verbose_name="Ekip",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kullanıcı",
                "verbose_name_plural": "Kullanıcılar",
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="İş Tanımı")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Detaylı Açıklama"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("yuksek", "Yüksek"),
                            ("orta", "Orta"),
                            ("dusuk", "Düşük"),
                        ],
                        max_length=20,
                        verbose_name="Öncelik",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("baslanmadi", "Başlanmadı"),
                            ("calisiliyor", "Üzerinde Çalışılıyor"),
                            ("duraklatildi", "Duraklatıldı"),
                            ("tamamlandi", "Tamamlandı"),
                            ("iptal", "İptal Edildi"),
                        ],
                        default="baslanmadi",
                        max_length=20,
                        verbose_name="İşin Durumu",
                    ),
                ),
                (
                    "size",
                    models.IntegerField(
                        choices=[
                            (1, "1 - En Düşük"),
                            (2, "2 - Düşük"),
                            (3, "3 - Orta"),
                            (4, "4 - Yüksek"),
                            (5, "5 - En Yüksek"),
                        ],
                        verbose_name="İş Büyüklüğü (1-5)",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Başlangıç Tarihi")),
                ("due_date", models.DateField(verbose_name="Tamamlanma Tarihi")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Oluşturulma Zamanı"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Son Güncelleme"),
                ),
                (
                    "planned_hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        verbose_name="Planlanan Süre (Saat)",
                    ),
                ),
                (
                    "spent_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=6,
                        verbose_name="Harcanan Süre (Saat)",
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Atanan Çalışan",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Oluşturan Yönetici",
                    ),
                ),
                (
                    "informees",
                    models.ManyToManyField(
                        blank=True,
                        related_name="informed_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Bilgilendirilecek Kişiler",
                    ),
                ),
                (
                    "partners",
                    models.ManyToManyField(
                        blank=True,
                        related_name="partner_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İş Ortakları",
                    ),
                ),
            ],
            options={
                "verbose_name": "Görev",
                "verbose_name_plural": "Görevler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=1, verbose_name="Sıra No"),
                ),
                (
                    "description",
                    models.CharField(max_length=300, verbose_name="Adım Açıklaması"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Tamamlandı mı?"),
                ),
                (
                    "estimated_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Tahmini Süre (Saat)",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmap",
                        to="core.task",
                        verbose_name="Bağlı Görev",
                    ),
                ),
            ],
            options={
                "verbose_name": "Yol Haritası Adımı",
                "verbose_name_plural": "Yol Haritası Adımları",
                "ordering": ["order"],
            },
        ),
    ]
