# Generated by Django 4.2.28 on 2026-02-14 12:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        verbose_name="Harcanan Süre (Saat)",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Tarih"),
                ),
                ("description", models.TextField(verbose_name="Yapılan İş Açıklaması")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to="core.task",
                        verbose_name="İlgili Görev",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Çalışan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Efor Kaydı",
                "verbose_name_plural": "Efor Kayıtları",
                "ordering": ["-date", "-created_at"],
            },
        ),
    ]
